routes:
  /style:
    layout: style
  /spring-2018: landing
collections:
  services: '/services/{slug}'
  locations: '/locations/{slug}'
  careers: '/careers/{slug}'
  blog: '/careers/{slug}'
taxonomies: [ ]
